version: '3.9'
services:
  huertos:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: huertos
    ports:
      - '4102:5555'
    env_file: .env